### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by InDieTasten** [Blackxes/SimpleTry#1]
Sieht ganz nice aus :+1: 
Schön dokumentiert. Ich werde sehr wahrscheinlich meine eigene Implementierung machen, da einige Dinge für mich nicht von belangen sind, und andere nicht ausreichend detailliert sind.

**Comment by Blackxes** [comment]
Bitte sage mir auch wenn was verbessert haben solltest oder etwas hinzufuegst. 
Würd dann das gegebenenfalls selbst einbauen unter meinem Programmierstil
